const Employee=[
    {
        id:'100',
        empName:'Anu',
        age:'25',
        designation:'Developer',
        salary:'35000'
    },
    {
        id:'101',
        empName:'Vinu',
        age:'29',
        designation:'Designer',
        salary:'23000'
    },
    {
        id:'102',
        empName:'Manu',
        age:'35',
        designation:'Tester',
        salary:'20000'
    },
    {
        id:'103',
        empName:'Sethu',
        age:'28',
        designation:'HR',
        salary:'25000'
    }
]
export default Employee